package main

var tmpl = `// Code generated by jackett-sync; DO NOT EDIT.

package {{.Package}}

type Tracker int

const (
	{{range $i, $tracker := .Trackers}}
		{{- if eq $i 0}}{{camelCase $tracker.Name}} Tracker = iota{{else}}
	{{ camelCase $tracker.Name -}}{{end}}{{end}}
)

var trackersString = map[string]Tracker{
	{{- range .Trackers }}
	"{{.ID}}": {{ camelCase .Name -}},{{ end }}
}

var trackers = map[Tracker]string{
	{{- range .Trackers }}
	{{ camelCase .Name -}}: "{{.ID}}",{{ end }}
}

// String display current tracker ID.
func (t Tracker) String() string {
	return trackers[t]
}

// FromString returns a tracker matching given name.
func FromString(tracker string) (Tracker, bool) {
	t, ok := trackersString[tracker]
	return t, ok
}
`
