// Code generated by jackett-sync; DO NOT EDIT.

package trackers

type Tracker int

const (
	Bittorrentfiles Tracker = iota
	ABtorrents
	AcervosAPI
	ACGRIP
	ACGsou
	AcidLounge
	AcrossTheTasman
	Aftershock
	AidoruOnline
	AitherAPI
	AmigosShareClub
	AnaschCc
	AniLibria
	AnimeFree
	AnimeClipse
	AnimeLayer
	AnimeWorldAPI
	AniRena
	AniSource
	ArabaFenice
	ArenaBG
	AsianCinema
	Audiences
	AudioBookBay
	AudioNews
	AussierulEs
	BackUps
	BadassTorrents
	BangumiMoe
	BeiTai
	BestCore
	BeyondHD
	Bibliotik
	BigFANGroup
	BitBzis
	BitBR
	BitCityReloaded
	Bitded
	Bithorlo
	BitHUmen
	BitRu
	BitSearch
	BitSexy
	Bitspyder
	BiTTuRK
	BlueBird
	BluesBrothers
	BlutopiaAPI
	BookTracker
	BootyTape
	Borgzelle
	BoxingTorrents
	BroadCity
	BrSocietyAPI
	BTDigg
	BTEtree
	BTMET
	BTmirror
	BTNext
	BTSCHOOL
	BTSOW
	BwTorrents
	BYRBT
	Byrutor
	Carpathians
	CarpHunter
	CartoonChaos
	CathodeRayTube
	Catorrent
	CCFBits
	CeskeForum
	CHDBits
	ChileBT
	Cinemageddon
	CinemaMovieSZT
	Cinematik
	Classix
	CloudTorrents
	CoastalCrew
	Comicat
	ConCen
	Concertos
	Cpasbien
	CpasbienClone
	CrackingPatching
	CrazyHD
	CrazySpirits
	CrnaBerza
	CrypticHaven
	DanishBytesAPI
	DariusTracker
	DarkShadow
	DataSceneAPI
	DataTalli
	Deildu
	Demonoid
	DesiTorrentsAPI
	DiabloTorrent
	DigitalCore
	DimeADozen
	DiscFan
	DivTeam
	Dmhy
	DocsPedia
	DragonworldReloaded
	DreamTracker
	DXP
	EbookParadijs
	EbooksShares
	EHentai
	EliteTorrentBiz
	Empornium
	EniaHD
	EShareNet
	EStone
	ExKinoRay
	ExtraTorrentSt
	ExtremeBits
	ExtremlymTorrents
	EXTTorrents
	EZTV
	FalkonVisionTeam
	FANOIN
	FantasticHeaven
	Fantastiko
	Femdomcult
	FenyarnyekTracker
	FileTracker
	FileListing
	FinElite
	FinVip
	FireBit
	FouDuCinema
	FreshMeat
	FrozenLayer
	FTUApps
	FunkyTorrents
	GamesTorrents
	GayTorrentsNet
	GayTorrentsOrg
	GAYtorrentRu
	GenerationFreeAPI
	GenesisMovement
	GFXPeers
	GigaTorrents
	Girotorrent
	GkTorrent
	GloDLS
	GreekDiamond
	GreekTeam
	GTorrentPro
	HaiDan
	Haitang
	HamsterStudio
	HappyFappy
	HawkeUno
	HDAI
	HDArea
	HDAtmos
	HDBits
	HDBitsCom
	HDC
	HDCenter
	HDChina
	HDCity
	HDCzTorrent
	HDDolby
	HDForever
	HDGalaKtik
	HDHome
	HDME
	HDMonkey
	HDOlimpoAPI
	HDOnly
	HDRoute
	HDSky
	HDSpain
	HDtime
	HDTorrentsIt
	HDTurk
	HDU
	HDZone
	HouseOfDevil
	HQSource
	HunTorrent
	IBit
	Idope
	IlCorsaroBlu
	IlCorsaroNero
	IlCorsaroVerde
	Immortuos
	Indietorrents
	InsaneTracker
	InternetArchive
	ITorrent
	IVTorrents
	JAVTorrent
	JPopsuki
	JPTV
	Karagarga
	KeepFriends
	KickasstorrentsTo
	KickasstorrentsWs
	Kinorun
	Kinozal
	Knaben
	Korsar
	KrazyZone
	Kufirc
	LastFiles
	LatTeamAPI
	LearnBits
	LearnFlakes
	LegitTorrents
	LemonHD
	LePornoInfo
	LeSaloon
	LibraNet
	LimeTorrents
	LimeTorrentsClone
	LinkoManija
	LinuxTracker
	LosslessClub
	MacTorrentsDownload
	MaDsRevolution
	MagicHeaven
	Magico
	Majompard
	MarineTracker
	MegamixTracker
	MegaPeer
	MeseVilg
	MetalTracker
	MicroBit
	Mikan
	Milkie
	MioBT
	MIRCrew
	MixtapeTorrent
	MMATorrents
	MNV
	MononokBT
	MouseBits
	MoviesDVDR
	Moviesite
	MovieTorrent
	MovieTorrentz
	MTeamTP
	MuziekFabriek
	MVGroupForum
	MVGroupMain
	MyPornClub
	MySpleen
	NBTorrents
	NetCosmo
	NetHD
	NewPCTMe
	TheNewRetro
	Newstudio
	NewstudioL
	Nipponsei
	Nitro
	NNTT
	NoNaMeClub
	NoNaMeClubL
	NyaaSi
	OMgWtFtrackr
	OnceSearch
	OneJAV
	OpenCD
	OpenSharing
	Ourbits
	OxTorrent
	ParnuXi
	PCTorrent
	Peeratiko
	PeerJunkies
	PeersFM
	PigNetwork
	PiratBit
	PiratBitL
	Pixelados
	PixelCove
	PolishSource
	Pornbay
	Pornbits
	Pornforall
	PornLeech
	PornoLive
	PornosLab
	Pornotor
	PornoTorrent
	Portugas
	PotUK
	ProAudioTorrents
	ProPorno
	ProStyleX
	PTerClub
	PTFiles
	PThome
	PTMSG
	PTSBAO
	PTTime
	PunksHorrorTracker
	PuntoTorrent
	PuroVicio
	PussyTorrents
	PuTao
	PuurHollands
	RacingForMe
	RainbowTracker
	Rapidzona
	RedBitsAPI
	RedStarTorrent
	ReelFLiXAPI
	ResurrectTheNet
	RGFootball
	RinTor
	RinTorNeT
	RiperAM
	RockBox
	RomanianMetalTorrents
	RPTorrents
	RUDUB
	RusMedia
	Rustorka
	RuTor
	RuTrackerRU
	SATClubbing
	ScenePalace
	SceneRush
	SDBits
	Seedoff
	SeleZen
	SexyPics
	ShanaProject
	ShareislandAPI
	Sharewood
	ShowRSS
	SiamBIT
	SkipTheCommercialsAPI
	SkipTheTrailers
	SkTorrentOrg
	SkTorrent
	Slosoul
	SnowPT
	SolidTorrents
	Sosulki
	SoulVoice
	SoundPark
	SpeedmasterHD
	SpeedTorrentReloaded
	SpiderTK
	SpiritOfRevolution
	SportHD
	SportsCult
	SpringSunday
	SugoiMusic
	SukebeiNyaaSi
	Superbits
	Swarmazon
	Tapochek
	Tasmanit
	TeamCTGame
	TeamHD
	TeamOS
	TellyTorrentAPI
	Teracod
	TheCrazyOnes
	TheAudioScene
	TheEmpire
	TheFallingAngels
	TheGeeks
	TheHorrorCharnel
	TheLeachZone
	Themixingbowl
	TheNewFun
	TheOccult
	ThePirateBay
	ThePlace
	TheScenePlace
	TheShinning
	TheShow
	TheVault
	TJUPT
	TLFBits
	TmGHuB
	TokyoToshokan
	Torlock
	Torlook
	TorrentExplosiv
	TorrentPirat
	TOrrentTuRK
	TorrentBD
	TorrentBy
	TorrentCCF
	TorrentDB
	TorrentDownload
	TorrentDownloads
	TorrentFunk
	TorrentGalaxy
	TorrentHR
	Torrenting
	TorrentKitty
	TorrentlandAPI
	TorrentleechPl
	TorrentLeech
	TorrentLT
	TorrentMasters
	TorrentOyunIndir
	TorrentParadise
	TorrentQQ
	TorrentSectorCrew
	TorrentSeedsAPI
	TorrentSir
	TorrentsLocal
	TorrentSurf
	Torrentv
	TorrentView
	TorrentWhiz
	TotallyKids
	ToTheGlory
	ToTheGloryCookie
	TranceTraffic
	Trezzor
	TribalMixes
	TurkSeed
	TurkTorrent
	Turktracker
	TVChaosUK
	TvRoad
	TwilightTorrents
	TwilightsZoom
	UHDBits
	Underverse
	UnionDHT
	UnionFansub
	Unlimitz
	Vizuk
	VSTHouse
	VSTTorrents
	WDT
	WhiteAngel
	WorldInHD
	WOOt
	XIteMe
	XBiT
	XthorAPI
	XWTClassics
	XWtorrents
	XxxAdultTorrent
	Xxxtor
	Xxxtorrents
	YDYPT
	YGGcookie
	YGGtorrent
	YourBittorrent
	YTS
	ZamundaNet
	ZelkaOrg
	Zetorrents
	ZOMB
	Ztracker
)

var trackersString = map[string]Tracker{
	"Bittorrentfiles":        Bittorrentfiles,
	"abtorrents":             ABtorrents,
	"acervos":                AcervosAPI,
	"acgrip":                 ACGRIP,
	"acgsou":                 ACGsou,
	"acidlounge":             AcidLounge,
	"acrossthetasman":        AcrossTheTasman,
	"aftershock":             Aftershock,
	"aidoruonline":           AidoruOnline,
	"aither-api":             AitherAPI,
	"amigosshare":            AmigosShareClub,
	"anaschcc":               AnaschCc,
	"anilibria":              AniLibria,
	"anime-free":             AnimeFree,
	"animeclipse":            AnimeClipse,
	"animelayer":             AnimeLayer,
	"animeworld-api":         AnimeWorldAPI,
	"aniRena":                AniRena,
	"anisource":              AniSource,
	"arabafenice":            ArabaFenice,
	"arenabg":                ArenaBG,
	"asiancinema":            AsianCinema,
	"audiences":              Audiences,
	"audiobookbay":           AudioBookBay,
	"audionews":              AudioNews,
	"aussierules":            AussierulEs,
	"backups":                BackUps,
	"badasstorrents":         BadassTorrents,
	"bangumi-moe":            BangumiMoe,
	"beitai":                 BeiTai,
	"bestcore":               BestCore,
	"beyond-hd":              BeyondHD,
	"bibliotik":              Bibliotik,
	"bigfangroup":            BigFANGroup,
	"bitbazis":               BitBzis,
	"bitbr":                  BitBR,
	"bitcityreloaded":        BitCityReloaded,
	"bitded":                 Bitded,
	"bithorlo":               Bithorlo,
	"bithumen":               BitHUmen,
	"bitru":                  BitRu,
	"bitsearch":              BitSearch,
	"bitsexy":                BitSexy,
	"bitspyder":              Bitspyder,
	"bitturk":                BiTTuRK,
	"bluebirdhd":             BlueBird,
	"bluesbrothers":          BluesBrothers,
	"blutopia-api":           BlutopiaAPI,
	"booktracker":            BookTracker,
	"bootytape":              BootyTape,
	"borgzelle":              Borgzelle,
	"boxingtorrents":         BoxingTorrents,
	"broadcity":              BroadCity,
	"brsociety-api":          BrSocietyAPI,
	"btdigg":                 BTDigg,
	"btetree":                BTEtree,
	"btmet":                  BTMET,
	"btmirror":               BTmirror,
	"btnext":                 BTNext,
	"btschool":               BTSCHOOL,
	"btsow":                  BTSOW,
	"bwtorrents":             BwTorrents,
	"byrbt":                  BYRBT,
	"byrutor":                Byrutor,
	"carpathians":            Carpathians,
	"carphunter":             CarpHunter,
	"cartoonchaos":           CartoonChaos,
	"cathoderaytube":         CathodeRayTube,
	"catorrent":              Catorrent,
	"ccfbits":                CCFBits,
	"ceskeforum":             CeskeForum,
	"chdbits":                CHDBits,
	"chilebt":                ChileBT,
	"cinemageddon":           Cinemageddon,
	"cinemamovies":           CinemaMovieSZT,
	"cinematik":              Cinematik,
	"classix":                Classix,
	"cloudtorrents":          CloudTorrents,
	"coastalcrew":            CoastalCrew,
	"comicat":                Comicat,
	"concen":                 ConCen,
	"concertos":              Concertos,
	"cpasbien":               Cpasbien,
	"cpasbienclone":          CpasbienClone,
	"crackingpatching":       CrackingPatching,
	"crazyhd":                CrazyHD,
	"crazyspirits":           CrazySpirits,
	"crnaberza":              CrnaBerza,
	"cryptichaven":           CrypticHaven,
	"danishbytes-api":        DanishBytesAPI,
	"dariustracker":          DariusTracker,
	"dark-shadow":            DarkShadow,
	"datascene-api":          DataSceneAPI,
	"datatalli":              DataTalli,
	"deildu":                 Deildu,
	"demonoid":               Demonoid,
	"desitorrents-api":       DesiTorrentsAPI,
	"diablotorrent":          DiabloTorrent,
	"digitalcore":            DigitalCore,
	"dimeadozen":             DimeADozen,
	"discfan":                DiscFan,
	"divteam":                DivTeam,
	"dmhy":                   Dmhy,
	"docspedia":              DocsPedia,
	"dragonworldreloaded":    DragonworldReloaded,
	"dreamtracker":           DreamTracker,
	"dxp":                    DXP,
	"ebookparadijs":          EbookParadijs,
	"ebooks-shares":          EbooksShares,
	"ehentai":                EHentai,
	"elitetorrent-biz":       EliteTorrentBiz,
	"empornium":              Empornium,
	"eniahd":                 EniaHD,
	"esharenet":              EShareNet,
	"estone":                 EStone,
	"exkinoray":              ExKinoRay,
	"extratorrent-st":        ExtraTorrentSt,
	"extremebits":            ExtremeBits,
	"extremlymtorrents":      ExtremlymTorrents,
	"exttorrents":            EXTTorrents,
	"eztv":                   EZTV,
	"falkonvisionteam":       FalkonVisionTeam,
	"fanoin":                 FANOIN,
	"fantasticheaven":        FantasticHeaven,
	"fantastiko":             Fantastiko,
	"femdomcult":             Femdomcult,
	"fenyarnyek-tracker":     FenyarnyekTracker,
	"file-tracker":           FileTracker,
	"filelisting":            FileListing,
	"finelite":               FinElite,
	"finvip":                 FinVip,
	"firebit":                FireBit,
	"fouducinema":            FouDuCinema,
	"freshmeat":              FreshMeat,
	"frozenlayer":            FrozenLayer,
	"ftuapps":                FTUApps,
	"funkytorrents":          FunkyTorrents,
	"gamestorrents":          GamesTorrents,
	"gay-torrents":           GayTorrentsNet,
	"gay-torrentsorg":        GayTorrentsOrg,
	"gaytorrentru":           GAYtorrentRu,
	"generationfree-api":     GenerationFreeAPI,
	"genesismovement":        GenesisMovement,
	"gfxpeers":               GFXPeers,
	"gigatorrents":           GigaTorrents,
	"girotorrent":            Girotorrent,
	"gktorrent":              GkTorrent,
	"glodls":                 GloDLS,
	"greekdiamond":           GreekDiamond,
	"greekteam":              GreekTeam,
	"gtorrentpro":            GTorrentPro,
	"haidan":                 HaiDan,
	"haitang":                Haitang,
	"hamsterstudio":          HamsterStudio,
	"happyfappy":             HappyFappy,
	"hawke-uno":              HawkeUno,
	"hdai":                   HDAI,
	"hdarea":                 HDArea,
	"hdatmos":                HDAtmos,
	"hdbits":                 HDBits,
	"hdbitscom":              HDBitsCom,
	"hdc":                    HDC,
	"hdcenter":               HDCenter,
	"hdchina":                HDChina,
	"hdcity":                 HDCity,
	"hdcztorrent":            HDCzTorrent,
	"hddolby":                HDDolby,
	"hdforever":              HDForever,
	"hdgalaktik":             HDGalaKtik,
	"hdhome":                 HDHome,
	"hdme":                   HDME,
	"hdmonkey":               HDMonkey,
	"hdolimpo-api":           HDOlimpoAPI,
	"hdonly":                 HDOnly,
	"hdroute":                HDRoute,
	"hdsky":                  HDSky,
	"hdspain":                HDSpain,
	"hdtime":                 HDtime,
	"hdtorrentsit":           HDTorrentsIt,
	"hdturk":                 HDTurk,
	"hdu":                    HDU,
	"hdzone":                 HDZone,
	"houseofdevil":           HouseOfDevil,
	"hqsource":               HQSource,
	"huntorrent":             HunTorrent,
	"ibit":                   IBit,
	"idope":                  Idope,
	"ilcorsaroblu":           IlCorsaroBlu,
	"ilcorsaronero":          IlCorsaroNero,
	"ilcorsaroverde":         IlCorsaroVerde,
	"immortuos":              Immortuos,
	"indietorrents":          Indietorrents,
	"insanetracker":          InsaneTracker,
	"internetarchive":        InternetArchive,
	"itorrent":               ITorrent,
	"iv-torrents":            IVTorrents,
	"jav-torrent":            JAVTorrent,
	"jpopsuki":               JPopsuki,
	"jptv":                   JPTV,
	"karagarga":              Karagarga,
	"keepfriends":            KeepFriends,
	"kickasstorrents-to":     KickasstorrentsTo,
	"kickasstorrents-ws":     KickasstorrentsWs,
	"kinorun":                Kinorun,
	"kinozal":                Kinozal,
	"knaben":                 Knaben,
	"korsar":                 Korsar,
	"krazyzone":              KrazyZone,
	"kufirc":                 Kufirc,
	"lastfiles":              LastFiles,
	"lat-team-api":           LatTeamAPI,
	"learnbits":              LearnBits,
	"learnflakes":            LearnFlakes,
	"legittorrents":          LegitTorrents,
	"lemonhd":                LemonHD,
	"lepornoinfo":            LePornoInfo,
	"lesaloon":               LeSaloon,
	"libranet":               LibraNet,
	"limetorrents":           LimeTorrents,
	"limetorrentsclone":      LimeTorrentsClone,
	"linkomanija":            LinkoManija,
	"linuxtracker":           LinuxTracker,
	"losslessclub":           LosslessClub,
	"mactorrentsdownload":    MacTorrentsDownload,
	"madsrevolution":         MaDsRevolution,
	"magicheaven":            MagicHeaven,
	"magico":                 Magico,
	"majomparade":            Majompard,
	"marinetracker":          MarineTracker,
	"megamixtracker":         MegamixTracker,
	"megapeer":               MegaPeer,
	"mesevilag":              MeseVilg,
	"metaltracker":           MetalTracker,
	"microbit":               MicroBit,
	"mikan":                  Mikan,
	"milkie":                 Milkie,
	"miobt":                  MioBT,
	"mircrew":                MIRCrew,
	"mixtapetorrent":         MixtapeTorrent,
	"mma-torrents":           MMATorrents,
	"mnv":                    MNV,
	"mononokebt":             MononokBT,
	"mousebits":              MouseBits,
	"moviesdvdr":             MoviesDVDR,
	"moviesite":              Moviesite,
	"movietorrent":           MovieTorrent,
	"movietorrentz":          MovieTorrentz,
	"mteamtp":                MTeamTP,
	"muziekfabriek":          MuziekFabriek,
	"mvgroupforum":           MVGroupForum,
	"mvgroupmain":            MVGroupMain,
	"mypornclub":             MyPornClub,
	"myspleen":               MySpleen,
	"nbtorrents":             NBTorrents,
	"netcosmo":               NetCosmo,
	"nethd":                  NetHD,
	"newpct-me":              NewPCTMe,
	"newretro":               TheNewRetro,
	"newstudio":              Newstudio,
	"newstudiol":             NewstudioL,
	"nipponsei":              Nipponsei,
	"nitro":                  Nitro,
	"nntt":                   NNTT,
	"noname-club":            NoNaMeClub,
	"noname-clubl":           NoNaMeClubL,
	"nyaasi":                 NyaaSi,
	"omgwtftrackr":           OMgWtFtrackr,
	"oncesearch":             OnceSearch,
	"onejav":                 OneJAV,
	"opencd":                 OpenCD,
	"opensharing":            OpenSharing,
	"ourbits":                Ourbits,
	"oxtorrent":              OxTorrent,
	"parnuxi":                ParnuXi,
	"pctorrent":              PCTorrent,
	"peeratiko":              Peeratiko,
	"peerjunkies":            PeerJunkies,
	"peersfm":                PeersFM,
	"pignetwork":             PigNetwork,
	"piratbit":               PiratBit,
	"piratbitl":              PiratBitL,
	"pixelados":              Pixelados,
	"pixelcove":              PixelCove,
	"polishsource":           PolishSource,
	"pornbay":                Pornbay,
	"pornbits":               Pornbits,
	"pornforall":             Pornforall,
	"pornleech":              PornLeech,
	"pornolive":              PornoLive,
	"pornoslab":              PornosLab,
	"pornotor":               Pornotor,
	"pornotorrent":           PornoTorrent,
	"portugas":               Portugas,
	"potuk":                  PotUK,
	"proaudiotorrents":       ProAudioTorrents,
	"proporno":               ProPorno,
	"prostylex":              ProStyleX,
	"pterclub":               PTerClub,
	"ptfiles":                PTFiles,
	"pthome":                 PThome,
	"ptmsg":                  PTMSG,
	"ptsbao":                 PTSBAO,
	"pttime":                 PTTime,
	"punkshorror":            PunksHorrorTracker,
	"puntotorrent":           PuntoTorrent,
	"purovicio":              PuroVicio,
	"pussytorrents":          PussyTorrents,
	"putao":                  PuTao,
	"puurhollands":           PuurHollands,
	"racingforme":            RacingForMe,
	"rainbowtracker":         RainbowTracker,
	"rapidzona":              Rapidzona,
	"redbits-api":            RedBitsAPI,
	"redstartorrent":         RedStarTorrent,
	"reelflix-api":           ReelFLiXAPI,
	"resurrectthenet":        ResurrectTheNet,
	"rgfootball":             RGFootball,
	"rintor":                 RinTor,
	"rintornet":              RinTorNeT,
	"riperam":                RiperAM,
	"RockBox":                RockBox,
	"romanianmetaltorrents":  RomanianMetalTorrents,
	"rptorrents":             RPTorrents,
	"rudub":                  RUDUB,
	"rus-media":              RusMedia,
	"rustorka":               Rustorka,
	"rutor":                  RuTor,
	"rutracker-ru":           RuTrackerRU,
	"satclubbing":            SATClubbing,
	"scenepalace":            ScenePalace,
	"scenerush":              SceneRush,
	"sdbits":                 SDBits,
	"seedoff":                Seedoff,
	"selezen":                SeleZen,
	"sexypics":               SexyPics,
	"shanaproject":           ShanaProject,
	"shareisland-api":        ShareislandAPI,
	"sharewood":              Sharewood,
	"showrss":                ShowRSS,
	"siambit":                SiamBIT,
	"skipthecommercials-api": SkipTheCommercialsAPI,
	"skipthetrailers":        SkipTheTrailers,
	"sktorrent-org":          SkTorrentOrg,
	"sktorrent":              SkTorrent,
	"slosoul":                Slosoul,
	"snowpt":                 SnowPT,
	"solidtorrents":          SolidTorrents,
	"sosulki":                Sosulki,
	"soulvoice":              SoulVoice,
	"soundpark":              SoundPark,
	"speedmasterhd":          SpeedmasterHD,
	"speedtorrentreloaded":   SpeedTorrentReloaded,
	"spidertk":               SpiderTK,
	"spiritofrevolution":     SpiritOfRevolution,
	"sporthd":                SportHD,
	"sportscult":             SportsCult,
	"springsunday":           SpringSunday,
	"sugoimusic":             SugoiMusic,
	"sukebeinyaasi":          SukebeiNyaaSi,
	"superbits":              Superbits,
	"swarmazon":              Swarmazon,
	"tapochek":               Tapochek,
	"tasmanit":               Tasmanit,
	"teamctgame":             TeamCTGame,
	"teamhd":                 TeamHD,
	"teamos":                 TeamOS,
	"tellytorrent-api":       TellyTorrentAPI,
	"teracod":                Teracod,
	"the-crazy-ones":         TheCrazyOnes,
	"theaudioscene":          TheAudioScene,
	"theempire":              TheEmpire,
	"thefallingangels":       TheFallingAngels,
	"thegeeks":               TheGeeks,
	"thehorrorcharnel":       TheHorrorCharnel,
	"theleachzone":           TheLeachZone,
	"themixingbowl":          Themixingbowl,
	"thenewfun":              TheNewFun,
	"theoccult":              TheOccult,
	"thepiratebay":           ThePirateBay,
	"theplace":               ThePlace,
	"thesceneplace":          TheScenePlace,
	"theshinning":            TheShinning,
	"theshow":                TheShow,
	"thevault":               TheVault,
	"tjupt":                  TJUPT,
	"tlfbits":                TLFBits,
	"tmghub":                 TmGHuB,
	"tokyotosho":             TokyoToshokan,
	"torlock":                Torlock,
	"torlook":                Torlook,
	"torrent-explosiv":       TorrentExplosiv,
	"torrent-pirat":          TorrentPirat,
	"torrent-turk":           TOrrentTuRK,
	"torrentbd":              TorrentBD,
	"torrentby":              TorrentBy,
	"torrentccf":             TorrentCCF,
	"torrentdb":              TorrentDB,
	"torrentdownload":        TorrentDownload,
	"torrentdownloads":       TorrentDownloads,
	"torrentfunk":            TorrentFunk,
	"torrentgalaxy":          TorrentGalaxy,
	"torrenthr":              TorrentHR,
	"torrenting":             Torrenting,
	"torrentkitty":           TorrentKitty,
	"torrentland-api":        TorrentlandAPI,
	"torrentleech-pl":        TorrentleechPl,
	"torrentleech":           TorrentLeech,
	"torrentlt":              TorrentLT,
	"torrentmasters":         TorrentMasters,
	"torrentoyunindir":       TorrentOyunIndir,
	"torrentparadise":        TorrentParadise,
	"torrentqq":              TorrentQQ,
	"torrentsectorcrew":      TorrentSectorCrew,
	"torrentseeds-api":       TorrentSeedsAPI,
	"torrentsir":             TorrentSir,
	"torrentslocal":          TorrentsLocal,
	"torrentsurf":            TorrentSurf,
	"torrentv":               Torrentv,
	"torrentview":            TorrentView,
	"torrentwhiz":            TorrentWhiz,
	"totallykids":            TotallyKids,
	"totheglory":             ToTheGlory,
	"totheglorycookie":       ToTheGloryCookie,
	"trancetraffic":          TranceTraffic,
	"trezzor":                Trezzor,
	"tribalmixes":            TribalMixes,
	"turkseed":               TurkSeed,
	"turktorrent":            TurkTorrent,
	"turktracker":            Turktracker,
	"tvchaosuk":              TVChaosUK,
	"tvroad":                 TvRoad,
	"twilight":               TwilightTorrents,
	"twilightszoom":          TwilightsZoom,
	"uhdbits":                UHDBits,
	"underversel":            Underverse,
	"uniondht":               UnionDHT,
	"unionfansub":            UnionFansub,
	"unlimitz":               Unlimitz,
	"vizuk":                  Vizuk,
	"vsthouse":               VSTHouse,
	"vsttorrents":            VSTTorrents,
	"wdt":                    WDT,
	"whiteangel":             WhiteAngel,
	"wihd":                   WorldInHD,
	"woot":                   WOOt,
	"xiteme":                 XIteMe,
	"xbit":                   XBiT,
	"xthor-api":              XthorAPI,
	"xwtclassics":            XWTClassics,
	"xwtorrents":             XWtorrents,
	"xxxadulttorrent":        XxxAdultTorrent,
	"xxxtor":                 Xxxtor,
	"xxxtorrents":            Xxxtorrents,
	"ydypt":                  YDYPT,
	"yggcookie":              YGGcookie,
	"yggtorrent":             YGGtorrent,
	"yourbittorrent":         YourBittorrent,
	"yts":                    YTS,
	"zamundanet":             ZamundaNet,
	"zelkaorg":               ZelkaOrg,
	"zetorrents":             Zetorrents,
	"zomb":                   ZOMB,
	"ztracker":               Ztracker,
}

var trackers = map[Tracker]string{
	Bittorrentfiles:       "Bittorrentfiles",
	ABtorrents:            "abtorrents",
	AcervosAPI:            "acervos",
	ACGRIP:                "acgrip",
	ACGsou:                "acgsou",
	AcidLounge:            "acidlounge",
	AcrossTheTasman:       "acrossthetasman",
	Aftershock:            "aftershock",
	AidoruOnline:          "aidoruonline",
	AitherAPI:             "aither-api",
	AmigosShareClub:       "amigosshare",
	AnaschCc:              "anaschcc",
	AniLibria:             "anilibria",
	AnimeFree:             "anime-free",
	AnimeClipse:           "animeclipse",
	AnimeLayer:            "animelayer",
	AnimeWorldAPI:         "animeworld-api",
	AniRena:               "aniRena",
	AniSource:             "anisource",
	ArabaFenice:           "arabafenice",
	ArenaBG:               "arenabg",
	AsianCinema:           "asiancinema",
	Audiences:             "audiences",
	AudioBookBay:          "audiobookbay",
	AudioNews:             "audionews",
	AussierulEs:           "aussierules",
	BackUps:               "backups",
	BadassTorrents:        "badasstorrents",
	BangumiMoe:            "bangumi-moe",
	BeiTai:                "beitai",
	BestCore:              "bestcore",
	BeyondHD:              "beyond-hd",
	Bibliotik:             "bibliotik",
	BigFANGroup:           "bigfangroup",
	BitBzis:               "bitbazis",
	BitBR:                 "bitbr",
	BitCityReloaded:       "bitcityreloaded",
	Bitded:                "bitded",
	Bithorlo:              "bithorlo",
	BitHUmen:              "bithumen",
	BitRu:                 "bitru",
	BitSearch:             "bitsearch",
	BitSexy:               "bitsexy",
	Bitspyder:             "bitspyder",
	BiTTuRK:               "bitturk",
	BlueBird:              "bluebirdhd",
	BluesBrothers:         "bluesbrothers",
	BlutopiaAPI:           "blutopia-api",
	BookTracker:           "booktracker",
	BootyTape:             "bootytape",
	Borgzelle:             "borgzelle",
	BoxingTorrents:        "boxingtorrents",
	BroadCity:             "broadcity",
	BrSocietyAPI:          "brsociety-api",
	BTDigg:                "btdigg",
	BTEtree:               "btetree",
	BTMET:                 "btmet",
	BTmirror:              "btmirror",
	BTNext:                "btnext",
	BTSCHOOL:              "btschool",
	BTSOW:                 "btsow",
	BwTorrents:            "bwtorrents",
	BYRBT:                 "byrbt",
	Byrutor:               "byrutor",
	Carpathians:           "carpathians",
	CarpHunter:            "carphunter",
	CartoonChaos:          "cartoonchaos",
	CathodeRayTube:        "cathoderaytube",
	Catorrent:             "catorrent",
	CCFBits:               "ccfbits",
	CeskeForum:            "ceskeforum",
	CHDBits:               "chdbits",
	ChileBT:               "chilebt",
	Cinemageddon:          "cinemageddon",
	CinemaMovieSZT:        "cinemamovies",
	Cinematik:             "cinematik",
	Classix:               "classix",
	CloudTorrents:         "cloudtorrents",
	CoastalCrew:           "coastalcrew",
	Comicat:               "comicat",
	ConCen:                "concen",
	Concertos:             "concertos",
	Cpasbien:              "cpasbien",
	CpasbienClone:         "cpasbienclone",
	CrackingPatching:      "crackingpatching",
	CrazyHD:               "crazyhd",
	CrazySpirits:          "crazyspirits",
	CrnaBerza:             "crnaberza",
	CrypticHaven:          "cryptichaven",
	DanishBytesAPI:        "danishbytes-api",
	DariusTracker:         "dariustracker",
	DarkShadow:            "dark-shadow",
	DataSceneAPI:          "datascene-api",
	DataTalli:             "datatalli",
	Deildu:                "deildu",
	Demonoid:              "demonoid",
	DesiTorrentsAPI:       "desitorrents-api",
	DiabloTorrent:         "diablotorrent",
	DigitalCore:           "digitalcore",
	DimeADozen:            "dimeadozen",
	DiscFan:               "discfan",
	DivTeam:               "divteam",
	Dmhy:                  "dmhy",
	DocsPedia:             "docspedia",
	DragonworldReloaded:   "dragonworldreloaded",
	DreamTracker:          "dreamtracker",
	DXP:                   "dxp",
	EbookParadijs:         "ebookparadijs",
	EbooksShares:          "ebooks-shares",
	EHentai:               "ehentai",
	EliteTorrentBiz:       "elitetorrent-biz",
	Empornium:             "empornium",
	EniaHD:                "eniahd",
	EShareNet:             "esharenet",
	EStone:                "estone",
	ExKinoRay:             "exkinoray",
	ExtraTorrentSt:        "extratorrent-st",
	ExtremeBits:           "extremebits",
	ExtremlymTorrents:     "extremlymtorrents",
	EXTTorrents:           "exttorrents",
	EZTV:                  "eztv",
	FalkonVisionTeam:      "falkonvisionteam",
	FANOIN:                "fanoin",
	FantasticHeaven:       "fantasticheaven",
	Fantastiko:            "fantastiko",
	Femdomcult:            "femdomcult",
	FenyarnyekTracker:     "fenyarnyek-tracker",
	FileTracker:           "file-tracker",
	FileListing:           "filelisting",
	FinElite:              "finelite",
	FinVip:                "finvip",
	FireBit:               "firebit",
	FouDuCinema:           "fouducinema",
	FreshMeat:             "freshmeat",
	FrozenLayer:           "frozenlayer",
	FTUApps:               "ftuapps",
	FunkyTorrents:         "funkytorrents",
	GamesTorrents:         "gamestorrents",
	GayTorrentsNet:        "gay-torrents",
	GayTorrentsOrg:        "gay-torrentsorg",
	GAYtorrentRu:          "gaytorrentru",
	GenerationFreeAPI:     "generationfree-api",
	GenesisMovement:       "genesismovement",
	GFXPeers:              "gfxpeers",
	GigaTorrents:          "gigatorrents",
	Girotorrent:           "girotorrent",
	GkTorrent:             "gktorrent",
	GloDLS:                "glodls",
	GreekDiamond:          "greekdiamond",
	GreekTeam:             "greekteam",
	GTorrentPro:           "gtorrentpro",
	HaiDan:                "haidan",
	Haitang:               "haitang",
	HamsterStudio:         "hamsterstudio",
	HappyFappy:            "happyfappy",
	HawkeUno:              "hawke-uno",
	HDAI:                  "hdai",
	HDArea:                "hdarea",
	HDAtmos:               "hdatmos",
	HDBits:                "hdbits",
	HDBitsCom:             "hdbitscom",
	HDC:                   "hdc",
	HDCenter:              "hdcenter",
	HDChina:               "hdchina",
	HDCity:                "hdcity",
	HDCzTorrent:           "hdcztorrent",
	HDDolby:               "hddolby",
	HDForever:             "hdforever",
	HDGalaKtik:            "hdgalaktik",
	HDHome:                "hdhome",
	HDME:                  "hdme",
	HDMonkey:              "hdmonkey",
	HDOlimpoAPI:           "hdolimpo-api",
	HDOnly:                "hdonly",
	HDRoute:               "hdroute",
	HDSky:                 "hdsky",
	HDSpain:               "hdspain",
	HDtime:                "hdtime",
	HDTorrentsIt:          "hdtorrentsit",
	HDTurk:                "hdturk",
	HDU:                   "hdu",
	HDZone:                "hdzone",
	HouseOfDevil:          "houseofdevil",
	HQSource:              "hqsource",
	HunTorrent:            "huntorrent",
	IBit:                  "ibit",
	Idope:                 "idope",
	IlCorsaroBlu:          "ilcorsaroblu",
	IlCorsaroNero:         "ilcorsaronero",
	IlCorsaroVerde:        "ilcorsaroverde",
	Immortuos:             "immortuos",
	Indietorrents:         "indietorrents",
	InsaneTracker:         "insanetracker",
	InternetArchive:       "internetarchive",
	ITorrent:              "itorrent",
	IVTorrents:            "iv-torrents",
	JAVTorrent:            "jav-torrent",
	JPopsuki:              "jpopsuki",
	JPTV:                  "jptv",
	Karagarga:             "karagarga",
	KeepFriends:           "keepfriends",
	KickasstorrentsTo:     "kickasstorrents-to",
	KickasstorrentsWs:     "kickasstorrents-ws",
	Kinorun:               "kinorun",
	Kinozal:               "kinozal",
	Knaben:                "knaben",
	Korsar:                "korsar",
	KrazyZone:             "krazyzone",
	Kufirc:                "kufirc",
	LastFiles:             "lastfiles",
	LatTeamAPI:            "lat-team-api",
	LearnBits:             "learnbits",
	LearnFlakes:           "learnflakes",
	LegitTorrents:         "legittorrents",
	LemonHD:               "lemonhd",
	LePornoInfo:           "lepornoinfo",
	LeSaloon:              "lesaloon",
	LibraNet:              "libranet",
	LimeTorrents:          "limetorrents",
	LimeTorrentsClone:     "limetorrentsclone",
	LinkoManija:           "linkomanija",
	LinuxTracker:          "linuxtracker",
	LosslessClub:          "losslessclub",
	MacTorrentsDownload:   "mactorrentsdownload",
	MaDsRevolution:        "madsrevolution",
	MagicHeaven:           "magicheaven",
	Magico:                "magico",
	Majompard:             "majomparade",
	MarineTracker:         "marinetracker",
	MegamixTracker:        "megamixtracker",
	MegaPeer:              "megapeer",
	MeseVilg:              "mesevilag",
	MetalTracker:          "metaltracker",
	MicroBit:              "microbit",
	Mikan:                 "mikan",
	Milkie:                "milkie",
	MioBT:                 "miobt",
	MIRCrew:               "mircrew",
	MixtapeTorrent:        "mixtapetorrent",
	MMATorrents:           "mma-torrents",
	MNV:                   "mnv",
	MononokBT:             "mononokebt",
	MouseBits:             "mousebits",
	MoviesDVDR:            "moviesdvdr",
	Moviesite:             "moviesite",
	MovieTorrent:          "movietorrent",
	MovieTorrentz:         "movietorrentz",
	MTeamTP:               "mteamtp",
	MuziekFabriek:         "muziekfabriek",
	MVGroupForum:          "mvgroupforum",
	MVGroupMain:           "mvgroupmain",
	MyPornClub:            "mypornclub",
	MySpleen:              "myspleen",
	NBTorrents:            "nbtorrents",
	NetCosmo:              "netcosmo",
	NetHD:                 "nethd",
	NewPCTMe:              "newpct-me",
	TheNewRetro:           "newretro",
	Newstudio:             "newstudio",
	NewstudioL:            "newstudiol",
	Nipponsei:             "nipponsei",
	Nitro:                 "nitro",
	NNTT:                  "nntt",
	NoNaMeClub:            "noname-club",
	NoNaMeClubL:           "noname-clubl",
	NyaaSi:                "nyaasi",
	OMgWtFtrackr:          "omgwtftrackr",
	OnceSearch:            "oncesearch",
	OneJAV:                "onejav",
	OpenCD:                "opencd",
	OpenSharing:           "opensharing",
	Ourbits:               "ourbits",
	OxTorrent:             "oxtorrent",
	ParnuXi:               "parnuxi",
	PCTorrent:             "pctorrent",
	Peeratiko:             "peeratiko",
	PeerJunkies:           "peerjunkies",
	PeersFM:               "peersfm",
	PigNetwork:            "pignetwork",
	PiratBit:              "piratbit",
	PiratBitL:             "piratbitl",
	Pixelados:             "pixelados",
	PixelCove:             "pixelcove",
	PolishSource:          "polishsource",
	Pornbay:               "pornbay",
	Pornbits:              "pornbits",
	Pornforall:            "pornforall",
	PornLeech:             "pornleech",
	PornoLive:             "pornolive",
	PornosLab:             "pornoslab",
	Pornotor:              "pornotor",
	PornoTorrent:          "pornotorrent",
	Portugas:              "portugas",
	PotUK:                 "potuk",
	ProAudioTorrents:      "proaudiotorrents",
	ProPorno:              "proporno",
	ProStyleX:             "prostylex",
	PTerClub:              "pterclub",
	PTFiles:               "ptfiles",
	PThome:                "pthome",
	PTMSG:                 "ptmsg",
	PTSBAO:                "ptsbao",
	PTTime:                "pttime",
	PunksHorrorTracker:    "punkshorror",
	PuntoTorrent:          "puntotorrent",
	PuroVicio:             "purovicio",
	PussyTorrents:         "pussytorrents",
	PuTao:                 "putao",
	PuurHollands:          "puurhollands",
	RacingForMe:           "racingforme",
	RainbowTracker:        "rainbowtracker",
	Rapidzona:             "rapidzona",
	RedBitsAPI:            "redbits-api",
	RedStarTorrent:        "redstartorrent",
	ReelFLiXAPI:           "reelflix-api",
	ResurrectTheNet:       "resurrectthenet",
	RGFootball:            "rgfootball",
	RinTor:                "rintor",
	RinTorNeT:             "rintornet",
	RiperAM:               "riperam",
	RockBox:               "RockBox",
	RomanianMetalTorrents: "romanianmetaltorrents",
	RPTorrents:            "rptorrents",
	RUDUB:                 "rudub",
	RusMedia:              "rus-media",
	Rustorka:              "rustorka",
	RuTor:                 "rutor",
	RuTrackerRU:           "rutracker-ru",
	SATClubbing:           "satclubbing",
	ScenePalace:           "scenepalace",
	SceneRush:             "scenerush",
	SDBits:                "sdbits",
	Seedoff:               "seedoff",
	SeleZen:               "selezen",
	SexyPics:              "sexypics",
	ShanaProject:          "shanaproject",
	ShareislandAPI:        "shareisland-api",
	Sharewood:             "sharewood",
	ShowRSS:               "showrss",
	SiamBIT:               "siambit",
	SkipTheCommercialsAPI: "skipthecommercials-api",
	SkipTheTrailers:       "skipthetrailers",
	SkTorrentOrg:          "sktorrent-org",
	SkTorrent:             "sktorrent",
	Slosoul:               "slosoul",
	SnowPT:                "snowpt",
	SolidTorrents:         "solidtorrents",
	Sosulki:               "sosulki",
	SoulVoice:             "soulvoice",
	SoundPark:             "soundpark",
	SpeedmasterHD:         "speedmasterhd",
	SpeedTorrentReloaded:  "speedtorrentreloaded",
	SpiderTK:              "spidertk",
	SpiritOfRevolution:    "spiritofrevolution",
	SportHD:               "sporthd",
	SportsCult:            "sportscult",
	SpringSunday:          "springsunday",
	SugoiMusic:            "sugoimusic",
	SukebeiNyaaSi:         "sukebeinyaasi",
	Superbits:             "superbits",
	Swarmazon:             "swarmazon",
	Tapochek:              "tapochek",
	Tasmanit:              "tasmanit",
	TeamCTGame:            "teamctgame",
	TeamHD:                "teamhd",
	TeamOS:                "teamos",
	TellyTorrentAPI:       "tellytorrent-api",
	Teracod:               "teracod",
	TheCrazyOnes:          "the-crazy-ones",
	TheAudioScene:         "theaudioscene",
	TheEmpire:             "theempire",
	TheFallingAngels:      "thefallingangels",
	TheGeeks:              "thegeeks",
	TheHorrorCharnel:      "thehorrorcharnel",
	TheLeachZone:          "theleachzone",
	Themixingbowl:         "themixingbowl",
	TheNewFun:             "thenewfun",
	TheOccult:             "theoccult",
	ThePirateBay:          "thepiratebay",
	ThePlace:              "theplace",
	TheScenePlace:         "thesceneplace",
	TheShinning:           "theshinning",
	TheShow:               "theshow",
	TheVault:              "thevault",
	TJUPT:                 "tjupt",
	TLFBits:               "tlfbits",
	TmGHuB:                "tmghub",
	TokyoToshokan:         "tokyotosho",
	Torlock:               "torlock",
	Torlook:               "torlook",
	TorrentExplosiv:       "torrent-explosiv",
	TorrentPirat:          "torrent-pirat",
	TOrrentTuRK:           "torrent-turk",
	TorrentBD:             "torrentbd",
	TorrentBy:             "torrentby",
	TorrentCCF:            "torrentccf",
	TorrentDB:             "torrentdb",
	TorrentDownload:       "torrentdownload",
	TorrentDownloads:      "torrentdownloads",
	TorrentFunk:           "torrentfunk",
	TorrentGalaxy:         "torrentgalaxy",
	TorrentHR:             "torrenthr",
	Torrenting:            "torrenting",
	TorrentKitty:          "torrentkitty",
	TorrentlandAPI:        "torrentland-api",
	TorrentleechPl:        "torrentleech-pl",
	TorrentLeech:          "torrentleech",
	TorrentLT:             "torrentlt",
	TorrentMasters:        "torrentmasters",
	TorrentOyunIndir:      "torrentoyunindir",
	TorrentParadise:       "torrentparadise",
	TorrentQQ:             "torrentqq",
	TorrentSectorCrew:     "torrentsectorcrew",
	TorrentSeedsAPI:       "torrentseeds-api",
	TorrentSir:            "torrentsir",
	TorrentsLocal:         "torrentslocal",
	TorrentSurf:           "torrentsurf",
	Torrentv:              "torrentv",
	TorrentView:           "torrentview",
	TorrentWhiz:           "torrentwhiz",
	TotallyKids:           "totallykids",
	ToTheGlory:            "totheglory",
	ToTheGloryCookie:      "totheglorycookie",
	TranceTraffic:         "trancetraffic",
	Trezzor:               "trezzor",
	TribalMixes:           "tribalmixes",
	TurkSeed:              "turkseed",
	TurkTorrent:           "turktorrent",
	Turktracker:           "turktracker",
	TVChaosUK:             "tvchaosuk",
	TvRoad:                "tvroad",
	TwilightTorrents:      "twilight",
	TwilightsZoom:         "twilightszoom",
	UHDBits:               "uhdbits",
	Underverse:            "underversel",
	UnionDHT:              "uniondht",
	UnionFansub:           "unionfansub",
	Unlimitz:              "unlimitz",
	Vizuk:                 "vizuk",
	VSTHouse:              "vsthouse",
	VSTTorrents:           "vsttorrents",
	WDT:                   "wdt",
	WhiteAngel:            "whiteangel",
	WorldInHD:             "wihd",
	WOOt:                  "woot",
	XIteMe:                "xiteme",
	XBiT:                  "xbit",
	XthorAPI:              "xthor-api",
	XWTClassics:           "xwtclassics",
	XWtorrents:            "xwtorrents",
	XxxAdultTorrent:       "xxxadulttorrent",
	Xxxtor:                "xxxtor",
	Xxxtorrents:           "xxxtorrents",
	YDYPT:                 "ydypt",
	YGGcookie:             "yggcookie",
	YGGtorrent:            "yggtorrent",
	YourBittorrent:        "yourbittorrent",
	YTS:                   "yts",
	ZamundaNet:            "zamundanet",
	ZelkaOrg:              "zelkaorg",
	Zetorrents:            "zetorrents",
	ZOMB:                  "zomb",
	Ztracker:              "ztracker",
}

// String display current tracker ID.
func (t Tracker) String() string {
	return trackers[t]
}

// FromString returns a tracker matching given name.
func FromString(tracker string) (Tracker, bool) {
	t, ok := trackersString[tracker]
	return t, ok
}
